### ISSUE TITLE
Adding specific time marks for topics

### ISSUE THREAD

**Issue by zoebisch** [learn-co-curriculum/activerecord-associations-video-review-aliasing-activerecord-associations#1]
I realized, what I believe would be a great and simple way to improve these videos in general would be to add time stamps for macro topics.  As a for-instance, in this video the first time that Avi speaks of "aliasing" it would be great to have a quick reference. 

With these fairly long videos, I have found on many occasions trying to jog back-and-forth to locate specific things that I was a little unclear on, or, moving forward in the material it would be stellar to have those specific topics at hand.

**Comment by gj** [comment]
Hi @zoebisch !

Unfortunately, we don't have the bandwidth right now to go through the videos and mark down when specific topics are discussed. If you're up for keeping track of topics in any video yourself, I'd be more than happy to add your notes to the lesson page. 🙂

**Comment by zoebisch** [comment]
Understandable.  Just figured I'd throw that out there for future
possibilities for improvement so there is a record!
