### ISSUE TITLE
Suggested Summary and Objectives

### ISSUE THREAD

**Issue by kyleblee** [learn-co-curriculum/activerecord-associations-video-review-aliasing-activerecord-associations#2]
_Suggested Summary_
- In this video we discuss the reasons for aliasing ActiveRecord associations and how you go about setting up, and using, these associations.

_Suggested Objectives_
- Explain why we alias ActiveRecord associations.
- Set up aliased associations with the _has_many_ and _belongs_to_ methods. 
- Understand why it is best to start building your models with the model that has the least number of dependencies. 
- Use _rails generate model <model name> <initial column name>_ to generate models in your project.
- Use the _options_ hash accepted by _belongs_to_ and _has_many_ to tell ActiveRecord which actual models / foreign keys the alias is referring to.
- Understand why the more you alias things, the more you need to tell ActiveRecord about the associations, because you are breaking the conventions that ActiveRecord defaults to.
- Use _create_ to instantiate an object that is pre-associated to another object.
- Use _build_ to instantiate an object that is pre-associated to another object.
- Use _find_ to search through a collection and find an object based on a condition supplied in the argument.

**Comment by curiositypaths** [comment]
Thank you for submitting your suggested summary and objectives.
