### ISSUE TITLE
Suggested Summary

### ISSUE THREAD

**Issue by thekevinhuang** [learn-co-curriculum/activerecord-associations-video-review-aliasing-activerecord-associations#4]
As an extension of the ActiveRecord associations that we have gone through in previous lessons, we continue in this lesson with the concept of Aliasing these associations and some potential situations that we may want to use this concept.

We start with a Post, Comment, User model where:

A User may have many Comments and Posts
A Post may have many Comments
A Post has an "Author"
A Comment has a "Commentor"

In the example above, from the program's perspective Author and Commentor are both just other names we might prefer to use over "User." The statement "A Post has a User" doesn't flow as well as "A Post has an Author."

This video teaches us how to alias associations and even classes to better fit our desires.

**Comment by curiositypaths** [comment]
Hi there,

Thank you for submitting your Suggested Summary.
